### ISSUE TITLE
multiple digit support with decimal points

### ISSUE THREAD

**Issue by Yasheshhc** [r4ghu/iOS-CoreML-MNIST#1]
@r4ghu Your demo is very helpful. I have follow your step by step article as well. 

Can you please provide me some hint / suggestion that how can I detect multiple digits with decimal points ?

Thanks in Advance.

**Comment by r4ghu** [comment]
Will definitely look into it. Can't guarantee quick updates/fixes because of other commitments.

**Comment by borisdjo** [comment]
Would it be possible to do multiple digit support (without decimals) on full-screen, as a commission? I sent an email to you if you might be interested.
